//! Language and typography tables used by the normalisation passes.
//!
//! Generated from usdb_syncer's `language_translations.py` and `constants.py` so that
//! normalisation output matches the reference tooling exactly. Regenerate rather than
//! hand-edit.

/// Maps a lower-cased language name or code to its canonical English name.
pub const LANGUAGE_TRANSLATIONS: [(&str, &str); 158] = [
    ("alemán", "German"),
    ("alemão", "German"),
    ("allemand", "German"),
    ("angielski", "English"),
    ("anglais", "English"),
    ("arabe", "Arabic"),
    ("arabic", "Arabic"),
    ("arabisch", "Arabic"),
    ("arabo", "Arabic"),
    ("arabski", "Arabic"),
    ("ceco", "Czech"),
    ("checo", "Czech"),
    ("chinese", "Chinese"),
    ("chinesisch", "Chinese"),
    ("chino", "Chinese"),
    ("chinois", "Chinese"),
    ("chinês", "Chinese"),
    ("chiński", "Chinese"),
    ("chorwacki", "Croatian"),
    ("cinese", "Chinese"),
    ("coreano", "Korean"),
    ("coréen", "Korean"),
    ("croata", "Croatian"),
    ("croate", "Croatian"),
    ("croatian", "Croatian"),
    ("croato", "Croatian"),
    ("czech", "Czech"),
    ("czeski", "Czech"),
    ("danese", "Danish"),
    ("danish", "Danish"),
    ("danois", "Danish"),
    ("danés", "Danish"),
    ("deutsch", "German"),
    ("dinamarquês", "Danish"),
    ("dutch", "Dutch"),
    ("duński", "Danish"),
    ("dänisch", "Danish"),
    ("englisch", "English"),
    ("english", "English"),
    ("eslovaco", "Slovak"),
    ("esloveno", "Slowenian"),
    ("espagnol", "Spanish"),
    ("espanhol", "Spanish"),
    ("español", "Spanish"),
    ("finlandese", "Finnish"),
    ("finlandés", "Finnish"),
    ("finlandês", "Finnish"),
    ("finnisch", "Finnish"),
    ("finnish", "Finnish"),
    ("finois", "Finnish"),
    ("fiński", "Finnish"),
    ("francese", "French"),
    ("francuski", "French"),
    ("francés", "French"),
    ("francês", "French"),
    ("französisch", "French"),
    ("français", "French"),
    ("french", "French"),
    ("german", "German"),
    ("giapponese", "Japanese"),
    ("hindi", "Hindi"),
    ("hiszpański", "Spanish"),
    ("holandés", "Dutch"),
    ("holandês", "Dutch"),
    ("holenderski", "Dutch"),
    ("hollandais", "Dutch"),
    ("holländisch", "Dutch"),
    ("indiano", "Hindi"),
    ("indien", "Hindi"),
    ("indio", "Hindi"),
    ("indisch", "Hindi"),
    ("indyjski", "Hindi"),
    ("inglese", "English"),
    ("inglés", "English"),
    ("inglês", "English"),
    ("italian", "Italian"),
    ("italiano", "Italian"),
    ("italien", "Italian"),
    ("italienisch", "Italian"),
    ("japanese", "Japanese"),
    ("japanisch", "Japanese"),
    ("japonais", "Japanese"),
    ("japonés", "Japanese"),
    ("japonês", "Japanese"),
    ("japoński", "Japanese"),
    ("korean", "Korean"),
    ("koreanisch", "Korean"),
    ("koreański", "Korean"),
    ("kroatisch", "Croatian"),
    ("lateinisch", "Latin"),
    ("latin", "Latin"),
    ("latino", "Latin"),
    ("niemiecki", "German"),
    ("noruego", "Norwegian"),
    ("norueguês", "Norwegian"),
    ("norvegese", "Norwegian"),
    ("norvégien", "Norwegian"),
    ("norwegian", "Norwegian"),
    ("norwegisch", "Norwegian"),
    ("norweski", "Norwegian"),
    ("olandese", "Dutch"),
    ("polacco,", "Polish"),
    ("polaco", "Polish"),
    ("polish", "Polish"),
    ("polnisch", "Polish"),
    ("polonais", "Polish"),
    ("polski", "Polish"),
    ("portoghese", "Portuguese"),
    ("portugais", "Portuguese"),
    ("portugalski", "Portuguese"),
    ("portugiesisch", "Portuguese"),
    ("portuguese", "Portuguese"),
    ("portugués", "Portuguese"),
    ("português", "Portuguese"),
    ("romanian", "Romanian"),
    ("romeno", "Romanian"),
    ("rosyjski", "Russian"),
    ("roumain", "Romanian"),
    ("rumano", "Romanian"),
    ("rumeno", "Romanian"),
    ("rumuński", "Romanian"),
    ("rumänisch", "Romanian"),
    ("ruski", "Russian"),
    ("ruso", "Russian"),
    ("russe", "Russian"),
    ("russian", "Russian"),
    ("russisch", "Russian"),
    ("russo", "Russian"),
    ("schwedisch", "Swedish"),
    ("slovacco", "Slovak"),
    ("slovak", "Slovak"),
    ("slovaque", "Slovak"),
    ("sloveno", "Slowenian"),
    ("slovène", "Slowenian"),
    ("slowakisch", "Slovak"),
    ("slowenian", "Slowenian"),
    ("slowenisch", "Slowenian"),
    ("spagnolo", "Spanish"),
    ("spanisch", "Spanish"),
    ("spanish", "Spanish"),
    ("sueco", "Swedish"),
    ("suédois", "Swedish"),
    ("svedese", "Swedish"),
    ("swedish", "Swedish"),
    ("szwedzki", "Swedish"),
    ("słowacki", "Slovak"),
    ("słoweński", "Slowenian"),
    ("tchèque", "Czech"),
    ("tedesco", "German"),
    ("tschechisch", "Czech"),
    ("turc", "Turkish"),
    ("turco", "Turkish"),
    ("turecki ", "Turkish"),
    ("turkish", "Turkish"),
    ("türkisch", "Turkish"),
    ("włoski", "Italian"),
    ("árabe", "Arabic"),
    ("łacina", "Latin"),
];

/// Opening and closing quotation marks per language.
pub const QUOTATION_MARKS: [(&str, char, char); 45] = [
    ("Bosnian", '”', '”'),
    ("Breton", '«', '»'),
    ("Catalan", '«', '»'),
    ("Chinese (romanized)", '“', '”'),
    ("Croatian", '„', '”'),
    ("Czech", '„', '“'),
    ("Danish", '»', '«'),
    ("Dutch", '„', '”'),
    ("English", '“', '”'),
    ("Estonian", '„', '“'),
    ("Finnish", '”', '”'),
    ("French", '«', '»'),
    ("Galician", '«', '»'),
    ("German", '»', '«'),
    ("Greek", '«', '»'),
    ("Greek (romanized)", '«', '»'),
    ("Hebrew", '„', '”'),
    ("Hindi", '“', '”'),
    ("Hindi (romanized)", '“', '”'),
    ("Hungarian", '„', '”'),
    ("Icelandic", '„', '“'),
    ("Indonesian", '“', '”'),
    ("Irish", '“', '”'),
    ("Italian", '«', '»'),
    ("Japanese", '「', '」'),
    ("Japanese (romanized)", '「', '」'),
    ("Korean", '“', '”'),
    ("Korean (romanized)", '“', '”'),
    ("Norwegian", '«', '»'),
    ("Polish", '„', '”'),
    ("Portuguese", '«', '»'),
    ("Portuguese (Brazil)", '“', '”'),
    ("Romanian", '„', '”'),
    ("Russian", '«', '»'),
    ("Russian (romanized)", '«', '»'),
    ("Scots", '“', '”'),
    ("Serbian", '„', '“'),
    ("Slovak", '„', '“'),
    ("Slovenian", '„', '“'),
    ("Spanish", '«', '»'),
    ("Swedish", '”', '”'),
    ("Turkish", '“', '”'),
    ("Ukrainian", '«', '»'),
    ("Vietnamese", '“', '”'),
    ("Welsh", '‘', '’'),
];

/// Characters treated as a generic quotation mark and replaced with the language pair.
pub const QUOTATION_MARKS_TO_REPLACE: [char; 8] = ['"', '«', '»', '“', '”', '„', '「', '」'];

/// Languages that put a narrow no-break space inside their quotation marks.
pub const LANGUAGES_WITH_SPACED_QUOTES: [&str; 2] = ["Breton", "French"];

/// Narrow no-break space, used inside French-style quotation marks.
pub const NARROW_NO_BREAK_SPACE: char = '\u{202f}';

/// Canonical English name for a language, or the input unchanged.
pub fn canonical_language(name: &str) -> String {
    let lower = name.to_lowercase();
    LANGUAGE_TRANSLATIONS
        .iter()
        .find(|(key, _)| *key == lower)
        .map_or_else(|| name.to_owned(), |(_, value)| (*value).to_owned())
}

/// Quotation marks for a language, defaulting to the English pair.
pub fn quotation_marks(language: &str) -> (char, char) {
    QUOTATION_MARKS
        .iter()
        .find(|(key, _, _)| *key == language)
        .map_or(('\u{201c}', '\u{201d}'), |(_, open, close)| (*open, *close))
}

/// Whether a language spaces its quotation marks.
pub fn has_spaced_quotes(language: &str) -> bool {
    LANGUAGES_WITH_SPACED_QUOTES.contains(&language)
}
