[package]
name = "rungstar-app"
description = "RungStar executables"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "rungstar"
path = "src/app.rs"

[[bin]]
name = "rungstar-diagnostics"
path = "src/diagnostics.rs"

[[bin]]
name = "rungstar-sing"
path = "src/sing.rs"

[dependencies]
rungstar-audio.workspace = true
rungstar-pitch.workspace = true
rungstar-platform.workspace = true
rungstar-song.workspace = true
rungstar-library.workspace = true
rungstar-ui.workspace = true
rungstar-score.workspace = true
sdl3 = { version = "0.18", features = ["unsafe_textures"] }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif", "bmp"] }
