[package]
name = "rungstar-platform"
description = "Window, input and audio devices via SDL3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rungstar-audio.workspace = true
rungstar-ui.workspace = true
fontdue = "0.9"
sdl3 = { version = "0.18", features = ["unsafe_textures"] }
thiserror.workspace = true
tracing.workspace = true
pollster = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { version = "26.0.1", default-features = false, features = ["std", "dx12", "wgsl"] }

[target.'cfg(target_os = "linux")'.dependencies]
sdl3 = { version = "0.18", features = ["unsafe_textures", "build-from-source"] }
wgpu = { version = "26.0.1", default-features = false, features = ["std", "vulkan", "gles", "wgsl"] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { version = "26.0.1", default-features = false, features = ["std", "metal", "wgsl"] }

[dev-dependencies]
tempfile = "3"
