[package]
name = "rungstar-platform"
description = "Window, input and audio devices via SDL3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rungstar-audio.workspace = true
rungstar-ui.workspace = true
fontdue = "0.9"
sdl3 = { version = "0.18", features = ["unsafe_textures"] }
thiserror.workspace = true
tracing.workspace = true
